version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: gardening-calendar
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    restart: unless-stopped
